apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: bookingapp
type: Opaque
data:
  JWT_SECRET: <your_jwt_secret>
  REDIS_PASSWORD: <your_redis_password>
  MONGODB_URI: <your_mongodb_uri>

